### PR TITLE
Rain on user placed snow should not accumulate

### LINKED ISSUE #7: Snow placed in non-snow biomes builds up in rain.
This is due to the code only checking for snowfall status if the snow block is nonexistent.
Snow layers only occurring in places where it is possible for snow to fall is a reasonable assumption and for all I know limiting that check might be a required optimization but I thought I should point it out just in case.

### PR DESCRIPTION
**Pull request by cam72cam**
Fixes #7

RFC @RandomlyAwesome

### CODE REVIEW

**Comment by RandomlyAwesome** [comment]
While this does fix #7 it seems that this check ignores the height based temperature change wherein it starts snowing over a certain height which changes depending on the biome.
This wouldn't normally be noticeable unless explicitly looked for but it prevents the more mountainous biomes from having snow accumulation(Extreme hills etc never went over the first layer while I was testing)

**Comment by cam72cam** [comment]
Can you point me at the code where snow happens above a certain elevation?  I am not finding that code in biome, chunk, or worldprovider?

I am also thinking of switching to .isSnowyBiome() instead.  Do you think that would be more accurate than checking the temperature?

**Comment by RandomlyAwesome** [comment]
The effect is that snow happens but the actual code works by reducing temperature values according to height above sea level,This happens in the getFloatTemperature function in Biome.
getTempCategory seems to be using getTemperature instead which doesn't factor in the reduction.
isSnowyBiome would cause the same problem as the biomes where the problem happens don't have that flag set anyways.
It appears that determining snow has accumulated into several redundant systems over the years

**Comment by cam72cam** [comment]
I dug into the code which the client uses to render snow particles and duplicated that.  Tested on a few worlds and it seemed to work just fine

**Pull request merged**
